import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** Tokens generados por Google Stitch (Tailwind v3). */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#0e1d26',
        'surface-tint': '#0f6682',
        'on-tertiary-fixed-variant': '#384a4e',
        'on-primary-fixed': '#001f2a',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#d7eaf0',
        'on-primary-container': '#c6ecff',
        'on-error-container': '#93000a',
        'surface-variant': '#d5e5f1',
        tertiary: '#405257',
        secondary: '#914d00',
        outline: '#70787d',
        'on-secondary-container': '#663500',
        'primary-fixed': '#bde9ff',
        'secondary-fixed-dim': '#ffb77d',
        'secondary-fixed': '#ffdcc3',
        'surface-container-low': '#e9f5ff',
        'outline-variant': '#bfc8cd',
        'on-primary': '#ffffff',
        surface: '#f5faff',
        'surface-dim': '#ccdce8',
        'on-secondary-fixed-variant': '#6e3900',
        'on-secondary': '#ffffff',
        'surface-bright': '#f5faff',
        'inverse-on-surface': '#e3f3ff',
        'on-primary-fixed-variant': '#004d64',
        'surface-container': '#e0f0fc',
        primary: '#00566f',
        'on-tertiary': '#ffffff',
        'primary-container': '#1f6f8b',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-secondary-fixed': '#2f1500',
        'tertiary-fixed': '#d3e6ec',
        'on-background': '#0e1d26',
        'secondary-container': '#fc9430',
        'tertiary-container': '#586a6f',
        'surface-container-high': '#daeaf7',
        background: '#f5faff',
        'inverse-primary': '#8ad0ef',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#0c1e22',
        'on-surface-variant': '#3f484d',
        'surface-container-highest': '#d5e5f1',
        'primary-fixed-dim': '#8ad0ef',
        'tertiary-fixed-dim': '#b7cad0',
        'inverse-surface': '#23323b',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'space-xs': '0.25rem', 'space-xl': '2rem', gutter: '1rem', 'margin-tablet': '1.5rem',
        'space-lg': '1.5rem', 'gutter-desktop': '1.5rem', 'margin-desktop': '2.5rem', margin: '1rem',
        'space-md': '1rem', 'space-sm': '0.5rem',
      },
      fontFamily: {
        sans: ['"Inter Variable"', 'Inter', 'system-ui', 'sans-serif'],
        'title-sm': ['Inter'], 'body-lg': ['Inter'], 'headline-md': ['Inter'], 'label-sm': ['Inter'],
        'headline-xl-mobile': ['Inter'], 'body-sm': ['Inter'], 'body-md': ['Inter'], 'headline-lg': ['Inter'],
        'title-md': ['Inter'], 'headline-xl': ['Inter'], 'label-md': ['Inter'],
      },
      fontSize: {
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
